### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by mathkimchi** [PeddieMathClub/PeddieMathClub.github.io#2]
Plz add dark mode

- [ ] dark mode
- [ ] make dark mode the default setting

**Comment by glolichen** [comment]
ok

**Comment by mathkimchi** [comment]
Any updates?

This "new" CSS feature might help: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark

**Comment by glolichen** [comment]
No
